name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:
resolution: workspace
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  get_it: 8.0.3
  http: 1.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
